os:
  - osx
  - linux
language: generic
sudo: required
dist: trusty
osx_image: xcode9.3
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/en/latest/install.sh)"
env:
  - SWIFT_VERSION=4.2
script:
  - swift test -c release -Xswiftc -enable-testing
notifications:
  email:
    on_success: never
    on_failure: change
